// This file is AUTO GENERATED by CMake.
#pragma once
#include "SDL_video.h"
const static char* FILENAME_CONFIG = "ux0:/data/cannonball/config.xml";
const static char* FILENAME_SCORES = "ux0:/data/cannonball/hiscores";
const static char* FILENAME_TTRIAL = "ux0:/data/cannonball/hiscores_timetrial";
const static char* FILENAME_CONT   = "ux0:/data/cannonball/hiscores_continuous";
const static int SDL_FLAGS = 0;
    